config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/', to: 'home#index'

  resources :developers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dev_lang.rb
class DevLang < ApplicationRecord
  belongs_to :developer
  belongs_to :language
end

app/models/dev_program.rb
class DevProgram < ApplicationRecord
  belongs_to :developers
  belongs_to :programming_languages
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :developer_languages
  has_many :languages, through: :developer_languages

  has_many :developer_programming_languages
  has_many :programming_languages, through: :developer_programming_languages
end

app/models/developer_language.rb
class DeveloperLanguage < ApplicationRecord
  belongs_to :developer
  belongs_to :language
end

app/models/developer_programming_language.rb
class DeveloperProgrammingLanguage < ApplicationRecord
  belongs_to :developer
  belongs_to :programming_language
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :developer_languages
  has_many :developers, through: :developer_languages
end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
  has_many :developer_programming_languages
  has_many :developers, through: :developer_programming_languages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: %i[show edit update destroy]

  # GET /developers
  # GET /developers.json
  def index
    @developers = Developer.all
  end

  # GET /developers/1
  # GET /developers/1.json
  def show
  end

  # GET /developers/new
  def new
    @developer = Developer.new
  end

  # GET /developers/1/edit
  def edit
  end

  # POST /developers
  # POST /developers.json
  def create
    @developer = Developer.new(developer_params)

    respond_to do |format|
      if @developer.save
        format.html { redirect_to @developer, notice: 'Developer was successfully created.' }
        format.json { render :show, status: :created, location: @developer }
      else
        format.html { render :new }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /developers/1
  # PATCH/PUT /developers/1.json
  def update
    respond_to do |format|
      if @developer.update(developer_params)
        format.html { redirect_to @developer, notice: 'Developer was successfully updated.' }
        format.json { render :show, status: :ok, location: @developer }
      else
        format.html { render :edit }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developers/1
  # DELETE /developers/1.json
  def destroy
    @developer.destroy
    respond_to do |format|
      format.html { redirect_to developers_url, notice: 'Developer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_developer
      @developer = Developer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def developer_params
      params.require(:developer).permit(:name, :email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ActiveModel::Model
  def index
    @form = DeveloperSearchForms.new(permitted_params)
    @developers = @form.search
  end

  private

  def permitted_params
    params.permit(developer_search_forms: DeveloperSearchForms::FORM_FIELDS)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/developers/_form.html.slim
= form_for @developer do |f|
  - if @developer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@developer.errors.count, "error")} prohibited this developer from being saved:"
      ul
        - @developer.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .actions = f.submit

app/views/developers/edit.html.slim
h1 Editing developer

== render 'form'

=> link_to 'Show', @developer
'|
=< link_to 'Back', developers_path

app/views/developers/index.html.slim
h1 Listing developers

table
  thead
    tr
      th Name
      th Email
      th
      th
      th

  tbody
    - @developers.each do |developer|
      tr
        td = developer.name
        td = developer.email
        td = link_to 'Show', developer
        td = link_to 'Edit', edit_developer_path(developer)
        td = link_to 'Destroy', developer, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Developer', new_developer_path

app/views/developers/new.html.slim
h1 New developer

== render 'form'

= link_to 'Back', developers_path

app/views/developers/show.html.slim
p#notice = notice

p
  strong Name:
  = @developer.name
p
  strong Email:
  = @developer.email

=> link_to 'Edit', edit_developer_path(@developer)
'|
=< link_to 'Back', developers_path

app/views/home/_form.html.slim
h4 Search Developers

= form_for @form, url: '/', method: :get do |f|
  .form-group.row
    = f.label :language_code, 'Language ', class: 'col-sm-3 col-form-label'
    = f.text_field :language_code
  .form-group.row
    = f.label :programming_language_name, 'Programming Language', class: 'col-sm-3 col-form-label'
    = f.text_field :programming_language_name
  .actions = f.submit 'Search', class: 'btn btn-primary'
br
- if @developers
  table.table.table-hover
    thead
      tr
        th Email
        th Programming Language
        th Languages

    tbody
      - @developers.each do |d|
        tr
          td = d.email
          td
            - d.programming_languages.each do |p|
              = p.name
              - unless p == d.programming_languages.last
                = ', '
          td
            - d.languages.each do |l|
              = l.code
              - unless l == d.languages.last
                = ', '

app/views/home/index.html.slim
h1 Find Developers

=render 'form'
br
br
=link_to 'Developers', developers_path
=>
= link_to 'Home', root_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | FindDevelopers
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield